name: Ping backend health

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          set -e
          echo "Pinging health endpoint"
          curl -fsS --max-time 10 https://zonagamer-backend.onrender.com/health || true
